#!/usr/bin/env sh
# run as regular user
set -e
mkdir /tmp/cascadia-code
cd /tmp/cascadia-code
wget https://github.com/microsoft/cascadia-code/releases/download/v2008.25/CascadiaCode-2008.25.zip &&
unzip /tmp/cascadia-code/CascadiaCode-2008.25.zip -d /tmp/cascadia-code/unzip
mkdir -p $HOME/.fonts/CascadiaCode-2008.25/otf/*
cp -rv /tmp/cascadia-code/unzip/otf/* $HOME/.fonts/CascadiaCode-2008.25/otf/
cd $HOME
rm -rf /tmp/cascadia-code
