#!/usr/bin/env sh

set -e

temp_path=/tmp/$(basename $@)$(date +%s)
mkdir $temp_path
cd $temp_path
wget https://github.com/microsoft/cascadia-code/releases/download/v2008.25/CascadiaCode-2008.25.zip &&
unzip $temp_path/CascadiaCode-2008.25.zip -d $temp_path/unzip
mkdir -p $HOME/.fonts/CascadiaCode-2008.25/otf/*
cp -rv $temp_path/unzip/otf/* $HOME/.fonts/CascadiaCode-2008.25/otf/
rm -rf $temp_path
